workflows:
  ios-build-and-export:
    name: iOS Build and Export
    scripts:
      - name: Install dependencies
        script: |
          pod install
      - name: Build and export IPA
        script: |
          xcodebuild \
          -workspace Stremio.xcworkspace \
          -scheme Stremio \
          -configuration Release \
          -destination generic/platform=iOS \
          archive
          xcodebuild \
          -exportArchive \
          -archivePath "Stremio.xcarchive" \
          -exportOptionsPlist exportOptions.plist \
          -exportPath "Stremio.ipa"
    environment:
      vars:
        PRODUCT_BUNDLE_IDENTIFIER: "com.limvo.stremio"
        PRODUCT_NAME: "Stremio"
        EXECUTABLE_NAME: "Stremio"
        DEVELOPMENT_LANGUAGE: "en"
        PRODUCT_BUNDLE_PACKAGE_TYPE: "com.apple.product-type.application"
    artifacts:
      paths:
        - Stremio.ipa
