# codemagic.yaml file

# Set Xcode and iOS versions
xcode_version: 13.4.1
ios_version: 15.4

# Set application information
app_name: stremio
app_scheme: .com.limvo.stremio

# Set build environment
build_environment:
  - MACOS_X_1
  
