# CodeMagic configuration for Stremio app

# Xcode project location
xcode_project: ios/Stremio.xcodeproj

# Scheme to build
scheme: Stremio

# Provisioning profile UUID
provisioning_profile_uuid: "YOUR_PROVISIONING_PROFILE_UUID"

# Build configuration
build_configuration: Release

# Output directory
output_directory: "$CM_BUILD_DIR/Stremio"

# Explicitly specify the bundle identifier
build_ios_app:
  params:
    bundle_identifier: "com.limvo.stremio"
