environment:
  vars:
    BUNDLE_ID: ".com.limvo.stremio"
    XCODE_WORKSPACE: "stremioios.xcworkspace"
    XCODE_SCHEME: "stremioios"
    APP_VERSION: "0.1"

scripts:
  - name: Build ipa for distribution
    script: |
      xcode-project build-ipa \
        --workspace "$CM_BUILD_DIR/$XCODE_WORKSPACE" \
        --scheme "$XCODE_SCHEME" \
        --configuration Release \
        --export-options EXPORT_PATH="build/ios/ipa" EXPORT_TYPE="ipa"

artifacts:
  - build/ios/ipa/*.ipa
  - /tmp/xcodebuild_logs/*.log
  - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
  - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

ios_signing:
  distribution_type: app_store
  bundle_identifier: $BUNDLE_ID
  version: $APP_VERSION
