workflows:
  ios:
    name: iOS Build
    instant_builds: true
    emails:
      - yousefalouri2002@gmail.com
    scripts:
      - name: Install dependencies
        script: |
          gem install cocoapods
          pod repo update
          pod install
      - name: Build IPA
        script: |
          xcodebuild clean -workspace Stremio.xcworkspace -scheme Stremio -configuration Release
          xcodebuild -exportArchive -archivePath Stremio.xcarchive -exportPath Stremio -exportFormat ipa -configuration Release
    artifacts:
      - Stremio.ipa
