workflows:
  ios-build:
    name: iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      variables:
        - name: BUNDLE_ID
          value: com.example.myapp
        - name: APP_VERSION
          value: 1.0.0
        - name: APP_BUILD_NUMBER
          value: 1
        - name: CODE_SIGN_IDENTITY
          value: iPhone Distribution
        - name: CODE_SIGN_PROVISIONING_PROFILE
          value: my_provisioning_profile
        - name: EXPO_RELEASE_CHANNEL
          value: default
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npx pod-install

      - name: Build IPA
        script: |
          npx expo build:ios -t app-store-ipa --configuration=release
          mv ios-build/Build/Products/AppStore/*.ipa $CM_BUILD_DIR/myapp.ipa

    artifacts:
      - myapp.ipa
